/**
 * Tests for the TypeScript ABI special-case fast path.
 *
 * Port of tests/test_parser_abi.py. Strict NodeNext ESM.
 *
 * -----
 * LIVE NOW (typescript grammar adapter landed)
 * -----
 * The ABI EXTRACTION fast-path tests run live. The TS grammar adapter exposes an
 * async `getExtractor()` (resolving the web-tree-sitter parser once) returning a
 * SYNC extract closure; the suite resolves it in beforeAll and the extraction
 * cases call it as `extract(src, "HeroAbi.ts")`, exactly mirroring the Python
 * `extract(src, "HeroAbi.ts")` calls.
 *
 * -----
 * STILL DEFERRED (TS port gaps in languages/typescript.ts — see impl bugs)
 * -----
 *  1. `_is_abi_file` is a MODULE-PRIVATE function in languages/typescript.ts (it
 *     is NOT exported), whereas python's typescript.py exposes it at module level
 *     so the detection tests can import it. The 6 `_is_abi_file(...)` detection
 *     cases therefore cannot be exercised in the TS port and stay it.skip.
 *  2. The `Extractor` closure returned by `getExtractor()` has the shape
 *     `(source, rel_path) => ...` and does NOT accept the Python `meta=` keyword
 *     (`abi_size_threshold` / `abi_max_symbols_per_file` overrides). The two
 *     meta-override cases therefore cannot be exercised and stay it.skip.
 *
 * Both are genuine porting gaps in src (not test issues); they are reported as
 * impl bugs and the affected cases remain it.skip with a precise reason.
 */
import { beforeAll, describe, expect, it } from "vitest";

import { getExtractor } from "../src/token_goat/languages/typescript.js";
import type { Extractor } from "../src/token_goat/parser.js";

// ---------------------------------------------------------------------------
// Helpers to build synthetic ABI files (ported verbatim from the Python module).
// ---------------------------------------------------------------------------

const _ABI_HEADER = Buffer.from("// AUTOGENERATED ABI - do not edit\n");

const _ABI_BODY = Buffer.from(`
export const HeroAbi = [
  {"inputs": [], "outputs": [{"name": "id", "type": "uint256"}], "name": "getHero", "type": "function"},
  {"inputs": [{"name": "id", "type": "uint256"}], "outputs": [], "name": "setHero", "type": "function"},
] as const;

export const QuestAbi = [
  {"inputs": [], "outputs": [{"name": "id", "type": "uint256"}], "name": "getQuest", "type": "function"},
] as const;

export interface HeroInterface {
  id: number;
}
`);

// ~190 KB worth of filler to cross the 100 KB threshold.
const _FILLER = Buffer.concat(Array.from({ length: 13000 }, () => Buffer.from("// filler line\n")));

function _largeAbiFile(): Buffer {
  return Buffer.concat([_ABI_HEADER, _ABI_BODY, _FILLER]);
}

function _smallAbiFile(): Buffer {
  // Same content but under the 100 KB threshold.
  return Buffer.concat([_ABI_HEADER, _ABI_BODY]);
}

const ABI_DETECT_REASON =
  "DEFERRED (TS port gap): _is_abi_file is module-private in " +
  "languages/typescript.ts (not exported); python's typescript.py exposes it at " +
  "module level. Re-enable when the TS adapter exports _is_abi_file.";

const ABI_META_REASON =
  "DEFERRED (TS port gap): the Extractor closure is (source, rel_path) and does " +
  "not accept the Python meta= overrides (abi_size_threshold / " +
  "abi_max_symbols_per_file). Re-enable when the TS adapter threads meta through.";

describe("test_parser_abi (port of tests/test_parser_abi.py)", () => {
  let extract: Extractor;

  beforeAll(async () => {
    extract = await getExtractor();
  });

  // -------------------------------------------------------------------------
  // _is_abi_file detection heuristics — DEFERRED (helper not exported)
  // -------------------------------------------------------------------------

  it.skip("test_large_autogenerated_header_detected", () => void ABI_DETECT_REASON);
  it.skip("test_small_file_not_detected", () => void ABI_DETECT_REASON);
  it.skip("test_abi_filename_suffix_detected", () => void ABI_DETECT_REASON);
  it.skip("test_abi_dot_ts_filename_detected", () => void ABI_DETECT_REASON);
  it.skip("test_abi_directory_detected", () => void ABI_DETECT_REASON);
  it.skip("test_as_const_with_abi_inputs_detected", () => void ABI_DETECT_REASON);
  it.skip("test_generated_header_variants", () => void ABI_DETECT_REASON);

  // -------------------------------------------------------------------------
  // ABI extraction fast path — LIVE
  // -------------------------------------------------------------------------

  it("test_abi_extract_returns_symbols_no_refs_no_imports", () => {
    const src = _largeAbiFile();
    const [symbols, refs, impExp] = extract(src, "HeroAbi.ts");
    expect(symbols.length).toBeGreaterThan(0);
    expect(refs.length).toBe(0);
    expect(impExp.length).toBe(0);
  });

  it("test_abi_symbols_have_correct_kind", () => {
    const src = _largeAbiFile();
    const [symbols] = extract(src, "HeroAbi.ts");
    for (const sym of symbols) {
      expect(sym.kind).toBe("abi_export");
    }
  });

  it("test_abi_exports_captured", () => {
    const src = _largeAbiFile();
    const [symbols] = extract(src, "HeroAbi.ts");
    const names = new Set(symbols.map((s) => s.name));
    expect(names.has("HeroAbi")).toBe(true);
    expect(names.has("QuestAbi")).toBe(true);
    expect(names.has("HeroInterface")).toBe(true);
  });

  it("test_abi_no_duplicate_symbols", () => {
    const src = _largeAbiFile();
    const [symbols] = extract(src, "HeroAbi.ts");
    const names = symbols.map((s) => s.name);
    expect(new Set(names).size).toBe(names.length);
  });

  it("test_abi_symbols_have_line_numbers", () => {
    const src = _largeAbiFile();
    const [symbols] = extract(src, "HeroAbi.ts");
    for (const sym of symbols) {
      expect(sym.line).toBeGreaterThanOrEqual(1);
    }
  });

  it("test_abi_symbols_have_signatures", () => {
    const src = _largeAbiFile();
    const [symbols] = extract(src, "HeroAbi.ts");
    for (const sym of symbols) {
      expect(sym.signature).not.toBeNull();
    }
  });

  it("test_small_file_falls_through_to_normal_extraction", () => {
    // A file under the threshold should NOT get abi_export kinds.
    const src = _smallAbiFile();
    const [symbols] = extract(src, "HeroAbi.ts");
    const abiSyms = symbols.filter((s) => s.kind === "abi_export");
    expect(abiSyms.length).toBe(0);
  });

  // -------------------------------------------------------------------------
  // meta-override cases — DEFERRED (Extractor closure has no meta param)
  // -------------------------------------------------------------------------

  it.skip("test_abi_max_symbols_cap", () => void ABI_META_REASON);
  it.skip("test_abi_size_threshold_meta_override", () => void ABI_META_REASON);
});
