"""Tests for the TypeScript ABI special-case fast path."""
from __future__ import annotations

from token_goat.languages.typescript import _is_abi_file, extract

# ---------------------------------------------------------------------------
# Helpers to build synthetic ABI files
# ---------------------------------------------------------------------------

_ABI_HEADER = b"// AUTOGENERATED ABI - do not edit\n"

_ABI_BODY = b"""
export const HeroAbi = [
  {"inputs": [], "outputs": [{"name": "id", "type": "uint256"}], "name": "getHero", "type": "function"},
  {"inputs": [{"name": "id", "type": "uint256"}], "outputs": [], "name": "setHero", "type": "function"},
] as const;

export const QuestAbi = [
  {"inputs": [], "outputs": [{"name": "id", "type": "uint256"}], "name": "getQuest", "type": "function"},
] as const;

export interface HeroInterface {
  id: number;
}
"""

# ~190 KB worth of filler to cross the 100 KB threshold
_FILLER = b"// filler line\n" * 13000


def _large_abi_file() -> bytes:
    return _ABI_HEADER + _ABI_BODY + _FILLER


def _small_abi_file() -> bytes:
    """Same content but under the 100 KB threshold."""
    return _ABI_HEADER + _ABI_BODY


# ---------------------------------------------------------------------------
# _is_abi_file detection heuristics
# ---------------------------------------------------------------------------


def test_large_autogenerated_header_detected():
    src = _large_abi_file()
    assert _is_abi_file(src, "hero.ts") is True


def test_small_file_not_detected():
    src = _small_abi_file()
    assert _is_abi_file(src, "hero.ts") is False


def test_abi_filename_suffix_detected():
    src = b"// AUTOGENERATED ABI\n" + _FILLER
    assert _is_abi_file(src, "contracts/HeroAbi.ts") is True


def test_abi_dot_ts_filename_detected():
    src = b"// AUTOGENERATED ABI\n" + _FILLER
    assert _is_abi_file(src, "contracts/hero.abi.ts") is True


def test_abi_directory_detected():
    src = b"// AUTOGENERATED ABI\n" + _FILLER
    assert _is_abi_file(src, "src/abi/hero.ts") is True


def test_as_const_with_abi_inputs_detected():
    """Files with many 'inputs':[] and as const patterns should be detected."""
    body = b'"inputs": [\n' * 6 + b'"outputs": [\n' * 4 + b"] as const;\n"
    src = body + _FILLER
    assert _is_abi_file(src, "generated.ts") is True


# ---------------------------------------------------------------------------
# ABI extraction fast path
# ---------------------------------------------------------------------------


def test_abi_extract_returns_symbols_no_refs_no_imports():
    src = _large_abi_file()
    symbols, refs, imp_exp, _ = extract(src, "HeroAbi.ts")
    assert len(symbols) > 0
    assert len(refs) == 0
    assert len(imp_exp) == 0


def test_abi_symbols_have_correct_kind():
    src = _large_abi_file()
    symbols, _, _, _ = extract(src, "HeroAbi.ts")
    for sym in symbols:
        assert sym.kind == "abi_export", f"{sym.name} has kind {sym.kind!r}, expected 'abi_export'"


def test_abi_exports_captured():
    src = _large_abi_file()
    symbols, _, _, _ = extract(src, "HeroAbi.ts")
    names = {s.name for s in symbols}
    assert "HeroAbi" in names
    assert "QuestAbi" in names
    assert "HeroInterface" in names


def test_abi_no_duplicate_symbols():
    src = _large_abi_file()
    symbols, _, _, _ = extract(src, "HeroAbi.ts")
    names = [s.name for s in symbols]
    assert len(names) == len(set(names)), "Duplicate symbols found in ABI output"


def test_abi_symbols_have_line_numbers():
    src = _large_abi_file()
    symbols, _, _, _ = extract(src, "HeroAbi.ts")
    for sym in symbols:
        assert sym.line >= 1, f"{sym.name} has line {sym.line}"


def test_abi_symbols_have_signatures():
    src = _large_abi_file()
    symbols, _, _, _ = extract(src, "HeroAbi.ts")
    for sym in symbols:
        assert sym.signature is not None, f"{sym.name} missing signature"


def test_small_file_falls_through_to_normal_extraction():
    """A file under the threshold should NOT get abi_export kinds."""
    src = _small_abi_file()
    symbols, refs, imp_exp, _ = extract(src, "HeroAbi.ts")
    abi_syms = [s for s in symbols if s.kind == "abi_export"]
    assert len(abi_syms) == 0, "Small file incorrectly treated as ABI"


def test_abi_max_symbols_cap():
    """abi_max_symbols_per_file meta knob should cap output."""
    # Build file with many exports
    many_exports = b"".join(
        f"export const Export{i} = [] as const;\n".encode() for i in range(600)
    )
    src = _ABI_HEADER + many_exports + _FILLER
    symbols, _, _, _ = extract(src, "big.ts", meta={"abi_max_symbols_per_file": 10})
    assert len(symbols) <= 10


def test_abi_size_threshold_meta_override():
    """abi_size_threshold meta knob lets callers lower the threshold."""
    src = _small_abi_file()  # only ~428 bytes
    # With threshold lowered to 100 bytes, should trigger ABI mode
    symbols, refs, _, _ = extract(src, "HeroAbi.ts", meta={"abi_size_threshold": 100})
    abi_syms = [s for s in symbols if s.kind == "abi_export"]
    assert len(abi_syms) > 0
    assert len(refs) == 0


def test_generated_header_variants():
    """Various autogenerated header strings should trigger detection."""
    headers = [
        b"// Generated by abigen. DO NOT EDIT.\n",
        b"// auto-generated by typechain\n",
        b"// AUTOGENERATED\n",
    ]
    for header in headers:
        src = header + _FILLER
        assert _is_abi_file(src, "contracts.ts") is True, f"Header not detected: {header!r}"
