"""Tests for the lockdeps command — lock file dep summarizer."""
from __future__ import annotations

import json
from pathlib import Path

import pytest

from token_goat.lockdeps import (
    LockResult,
    format_lockdeps_json,
    format_lockdeps_text,
    summarize_lockfile,
)

# ---------------------------------------------------------------------------
# Sample lock file content (inline strings — no disk I/O fixtures)
# ---------------------------------------------------------------------------

_POETRY = """\
[[package]]
name = "requests"
version = "2.31.0"
description = "HTTP library"

[[package]]
name = "certifi"
version = "2024.1.1"
description = "Mozilla CA bundle"

[[package]]
name = "old-sdk"
version = "1.0.0"
optional = true
"""

_UV = """\
# This file is automatically @generated by uv
[[package]]
name = "httpx"
version = "0.27.0"

[[package]]
name = "anyio"
version = "4.3.0"
"""

_REQUIREMENTS = """\
# production deps
requests==2.31.0
certifi>=2024.0
# dev
pytest==8.1.0  ; python_version >= "3.8"
"""

_PIPFILE = json.dumps({
    "default": {
        "requests": {"version": "==2.31.0", "hashes": []},
        "certifi": {"version": "==2024.1.1"},
    },
    "develop": {
        "pytest": {"version": "==8.1.0"},
    },
})

_CARGO = """\
[[package]]
name = "serde"
version = "1.0.200"
source = "registry+..."

[[package]]
name = "tokio"
version = "1.37.0"
source = "registry+..."
"""

_NPM_V2 = json.dumps({
    "lockfileVersion": 2,
    "packages": {
        "": {"dependencies": {"lodash": "^4.17"}},
        "node_modules/lodash": {"version": "4.17.21"},
        "node_modules/lodash/node_modules/deep": {"version": "1.0.0"},
    },
})


# ---------------------------------------------------------------------------
# Helper: write content to tmp file with a given name
# ---------------------------------------------------------------------------


def _write(tmp_path: Path, name: str, content: str) -> Path:
    p = tmp_path / name
    p.write_text(content, encoding="utf-8")
    return p


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------


class TestPoetry:
    def test_parses_packages(self, tmp_path):
        result = summarize_lockfile(_write(tmp_path, "poetry.lock", _POETRY))
        assert result.format == "poetry"
        names = {e.name for e in result.entries}
        assert "requests" in names and "certifi" in names

    def test_skips_optional(self, tmp_path):
        result = summarize_lockfile(_write(tmp_path, "poetry.lock", _POETRY))
        assert "old-sdk" not in {e.name for e in result.entries}

    def test_versions_correct(self, tmp_path):
        result = summarize_lockfile(_write(tmp_path, "poetry.lock", _POETRY))
        req = next(e for e in result.entries if e.name == "requests")
        assert req.version == "2.31.0"


class TestUv:
    def test_format_detection(self, tmp_path):
        result = summarize_lockfile(_write(tmp_path, "uv.lock", _UV))
        assert result.format == "uv"

    def test_parses_entries(self, tmp_path):
        result = summarize_lockfile(_write(tmp_path, "uv.lock", _UV))
        assert {e.name for e in result.entries} == {"httpx", "anyio"}


class TestRequirements:
    def test_parses_pinned(self, tmp_path):
        result = summarize_lockfile(_write(tmp_path, "requirements.txt", _REQUIREMENTS))
        names = {e.name for e in result.entries}
        assert "requests" in names

    def test_version_stripped(self, tmp_path):
        result = summarize_lockfile(_write(tmp_path, "requirements.txt", _REQUIREMENTS))
        req = next(e for e in result.entries if e.name == "requests")
        assert req.version == "2.31.0"

    def test_skips_comments(self, tmp_path):
        result = summarize_lockfile(_write(tmp_path, "requirements.txt", _REQUIREMENTS))
        assert all(not e.name.startswith("#") for e in result.entries)


class TestPipfile:
    def test_format_detection(self, tmp_path):
        result = summarize_lockfile(_write(tmp_path, "Pipfile.lock", _PIPFILE))
        assert result.format == "pipfile"

    def test_default_only(self, tmp_path):
        result = summarize_lockfile(_write(tmp_path, "Pipfile.lock", _PIPFILE))
        names = {e.name for e in result.entries}
        assert "requests" in names and "pytest" not in names


class TestCargo:
    def test_format_detection(self, tmp_path):
        result = summarize_lockfile(_write(tmp_path, "Cargo.lock", _CARGO))
        assert result.format == "cargo"

    def test_parses_entries(self, tmp_path):
        result = summarize_lockfile(_write(tmp_path, "Cargo.lock", _CARGO))
        assert {e.name for e in result.entries} == {"serde", "tokio"}


class TestNpm:
    def test_parses_direct_only(self, tmp_path):
        result = summarize_lockfile(_write(tmp_path, "package-lock.json", _NPM_V2))
        names = {e.name for e in result.entries}
        assert "lodash" in names
        assert "deep" not in names  # nested dep should be excluded


class TestFormatters:
    @pytest.fixture(scope="class")
    def result(self, tmp_path_factory):
        tmp = tmp_path_factory.mktemp("lockdeps")
        return summarize_lockfile(_write(tmp, "requirements.txt", _REQUIREMENTS))

    def test_text_has_header(self, result):
        out = format_lockdeps_text(result)
        assert "Package" in out and "Version" in out

    def test_text_has_count(self, result):
        assert "package(s)" in format_lockdeps_text(result)

    def test_empty_message(self):
        assert "No dependencies" in format_lockdeps_text(LockResult(format="requirements"))

    def test_json_structure(self, result):
        data = json.loads(format_lockdeps_json(result))
        assert "packages" in data and "format" in data
        assert all("name" in p and "version" in p for p in data["packages"])
