/**
 * Tests for CopilotFilter (standalone copilot binary) and GhCopilotFilter
 * improvements.
 *
 * 1:1 port of tests/test_bash_compress_copilot.py. The Python test classes
 * (TestCopilotStandaloneMatches, TestCopilotStandaloneCompress,
 * TestGhCopilotSuggestWithTarget, TestGhCopilotMatchesSubcommands) map to
 * describe() blocks of the same name; the module-level `def test_*` functions
 * map to top-level `it()`s. Every test keeps the SAME name and assertion
 * polarity as its Python counterpart.
 *
 * Test-seam mapping (Python -> TS):
 *  - `from token_goat.bash_compress import FILTERS, CopilotFilter,
 *    GhCopilotFilter, detect_from_command` -> named imports from the barrel.
 *  - `from token_goat import bash_compress` (inside one test) -> `import * as bc`.
 *  - `setup_method` assigning `self.f = ...Filter()` (and `self.argv`) -> a fresh
 *    `new ...Filter()` const inside each `it()`, matching the per-method setup.
 *  - `detect_from_command(cmd)` returns `(filter, argv)` or `None` -> the TS
 *    barrel returns `[filter, argv]` or `null`; we assert non-null then read
 *    `result[0].name`.
 *
 * Byte-exactness: the savings test divides `len(result.encode())` by
 * `len(_COPILOT_STANDALONE_EXPLAIN.encode())`; both are computed here from the
 * UTF-8 byte length via Buffer.byteLength, so the ratio matches the Python
 * computation exactly. The remaining assertions are substring checks on the
 * compress() output (pure-ASCII fixtures aside from the `•`/`?`/`>` glyphs,
 * same Unicode codepoints as the Python source).
 */
import { Buffer } from "node:buffer";

import { describe, expect, it } from "vitest";

import * as bc from "../src/token_goat/bash_compress.js";
import {
  CopilotFilter,
  FILTERS,
  GhCopilotFilter,
  detect_from_command,
} from "../src/token_goat/bash_compress.js";

// ---------------------------------------------------------------------------
// Sample output fixtures
// ---------------------------------------------------------------------------

const _COPILOT_STANDALONE_EXPLAIN = `
GitHub Copilot v1.0.3
Authenticated as: octocat

Generating...

Explanation:

  • git stash saves uncommitted changes to a stack.
  • Use git stash pop to restore them.
  • git stash list shows all stashes.

Disclaimer: AI-generated content. Always verify.
Note: Feedback at https://gh.io/copilot-feedback
`;

const _GH_COPILOT_SUGGEST_WITH_TARGET = `
Welcome to GitHub Copilot in the CLI!
Asking GitHub Copilot...

Suggested command:

  git stash

? Select an option  [Use arrows to move, type to filter]
> Copy command to clipboard
  Explain command
  Exit

Disclaimer: This response was generated by AI.
Always review AI-generated commands before running them.
`;

// ---------------------------------------------------------------------------
// CopilotFilter — matches()
// ---------------------------------------------------------------------------

describe("TestCopilotStandaloneMatches", () => {
  it("test_matches_bare_binary", () => {
    const f = new CopilotFilter();
    expect(f.matches(["copilot"])).toBeTruthy();
  });

  it("test_matches_explain_subcommand", () => {
    const f = new CopilotFilter();
    expect(f.matches(["copilot", "explain", "git stash"])).toBeTruthy();
  });

  it("test_matches_suggest_subcommand", () => {
    const f = new CopilotFilter();
    expect(f.matches(["copilot", "suggest", "list files"])).toBeTruthy();
  });

  it("test_does_not_match_gh_copilot", () => {
    // gh copilot is GhCopilotFilter's territory, not ours.
    const f = new CopilotFilter();
    expect(f.matches(["gh", "copilot", "explain"])).toBeFalsy();
  });

  it("test_does_not_match_empty", () => {
    const f = new CopilotFilter();
    expect(f.matches([])).toBeFalsy();
  });

  it("test_does_not_match_unrelated_binary", () => {
    const f = new CopilotFilter();
    expect(f.matches(["npm", "install"])).toBeFalsy();
  });
});

// ---------------------------------------------------------------------------
// CopilotFilter — compress()
// ---------------------------------------------------------------------------

describe("TestCopilotStandaloneCompress", () => {
  const argv = ["copilot", "explain", "git stash"];
  const _compress = (
    f: CopilotFilter,
    stdout: string = _COPILOT_STANDALONE_EXPLAIN,
  ): string => f.compress(stdout, "", 0, argv);

  it("test_drops_banner", () => {
    const f = new CopilotFilter();
    const result = _compress(f);
    expect(result).not.toContain("GitHub Copilot v1.0.3");
    expect(result).not.toContain("Authenticated as: octocat");
  });

  it("test_drops_spinner", () => {
    const f = new CopilotFilter();
    const result = _compress(f);
    expect(result).not.toContain("Generating...");
  });

  it("test_drops_disclaimer", () => {
    const f = new CopilotFilter();
    const result = _compress(f);
    expect(result).not.toContain("Disclaimer:");
    expect(result).not.toContain("Note:");
  });

  it("test_keeps_explanation_body", () => {
    const f = new CopilotFilter();
    const result = _compress(f);
    expect(result).toContain("git stash saves uncommitted changes");
    expect(result).toContain("git stash pop");
    expect(result).toContain("git stash list");
  });

  it("test_savings_at_least_25_percent", () => {
    const f = new CopilotFilter();
    const result = _compress(f);
    const original = Buffer.byteLength(_COPILOT_STANDALONE_EXPLAIN, "utf8");
    const compressed = Buffer.byteLength(result, "utf8");
    const savings = 1.0 - compressed / original;
    expect(savings).toBeGreaterThanOrEqual(0.25);
  });
});

// ---------------------------------------------------------------------------
// Registration checks
// ---------------------------------------------------------------------------

it("test_copilot_registered_in_filters", () => {
  const names = FILTERS.map((f) => f.name);
  expect(names).toContain("copilot");
});

it("test_copilot_in_all_exports", () => {
  expect(bc.__all__).toContain("CopilotFilter");
});

it("test_copilot_filter_adjacent_to_gh_copilot_filter", () => {
  // CopilotFilter should immediately follow GhCopilotFilter in FILTERS.
  const names = FILTERS.map((f) => f.name);
  const gh_idx = names.indexOf("gh-copilot");
  const cop_idx = names.indexOf("copilot");
  expect(cop_idx).toBe(gh_idx + 1);
});

// ---------------------------------------------------------------------------
// detect_from_command routing
// ---------------------------------------------------------------------------

it("test_dispatch_routes_copilot_standalone", () => {
  const result = detect_from_command("copilot explain 'git stash'");
  expect(result).not.toBeNull();
  const [f] = result!;
  expect(f.name).toBe("copilot");
});

it("test_dispatch_does_not_route_gh_copilot_to_standalone", () => {
  const result = detect_from_command("gh copilot explain 'git stash'");
  expect(result).not.toBeNull();
  const [f] = result!;
  expect(f.name).toBe("gh-copilot");
});

// ---------------------------------------------------------------------------
// GhCopilotFilter improvements
// ---------------------------------------------------------------------------

describe("TestGhCopilotSuggestWithTarget", () => {
  // GhCopilotFilter should keep the 'Suggested command:' header.
  const argv = ["gh", "copilot", "suggest", "--target", "shell", "list files"];

  it("test_keeps_suggested_command_header", () => {
    const f = new GhCopilotFilter();
    const result = f.compress(_GH_COPILOT_SUGGEST_WITH_TARGET, "", 0, argv);
    expect(result).toContain("Suggested command:");
  });

  it("test_keeps_the_actual_command", () => {
    const f = new GhCopilotFilter();
    const result = f.compress(_GH_COPILOT_SUGGEST_WITH_TARGET, "", 0, argv);
    expect(result).toContain("git stash");
  });

  it("test_drops_welcome_banner", () => {
    const f = new GhCopilotFilter();
    const result = f.compress(_GH_COPILOT_SUGGEST_WITH_TARGET, "", 0, argv);
    expect(result).not.toContain("Welcome to GitHub Copilot");
  });

  it("test_drops_spinner", () => {
    const f = new GhCopilotFilter();
    const result = f.compress(_GH_COPILOT_SUGGEST_WITH_TARGET, "", 0, argv);
    expect(result).not.toContain("Asking GitHub Copilot");
  });

  it("test_drops_disclaimer", () => {
    const f = new GhCopilotFilter();
    const result = f.compress(_GH_COPILOT_SUGGEST_WITH_TARGET, "", 0, argv);
    expect(result).not.toContain("Disclaimer:");
    expect(result).not.toContain("Always review");
  });
});

describe("TestGhCopilotMatchesSubcommands", () => {
  it("test_does_not_match_alias_subcommand", () => {
    const f = new GhCopilotFilter();
    expect(f.matches(["gh", "copilot", "alias", "bash"])).toBeFalsy();
  });

  it("test_does_not_match_feedback_subcommand", () => {
    const f = new GhCopilotFilter();
    expect(f.matches(["gh", "copilot", "feedback"])).toBeFalsy();
  });

  it("test_matches_explain", () => {
    const f = new GhCopilotFilter();
    expect(f.matches(["gh", "copilot", "explain", "git stash"])).toBeTruthy();
  });

  it("test_matches_suggest", () => {
    const f = new GhCopilotFilter();
    expect(f.matches(["gh", "copilot", "suggest", "list files"])).toBeTruthy();
  });
});
