"""Tests for CopilotFilter (standalone copilot binary) and GhCopilotFilter improvements."""

from __future__ import annotations

from token_goat.bash_compress import (
    FILTERS,
    CopilotFilter,
    GhCopilotFilter,
    detect_from_command,
)

# ---------------------------------------------------------------------------
# Sample output fixtures
# ---------------------------------------------------------------------------

_COPILOT_STANDALONE_EXPLAIN = """
GitHub Copilot v1.0.3
Authenticated as: octocat

Generating...

Explanation:

  • git stash saves uncommitted changes to a stack.
  • Use git stash pop to restore them.
  • git stash list shows all stashes.

Disclaimer: AI-generated content. Always verify.
Note: Feedback at https://gh.io/copilot-feedback
"""

_GH_COPILOT_SUGGEST_WITH_TARGET = """
Welcome to GitHub Copilot in the CLI!
Asking GitHub Copilot...

Suggested command:

  git stash

? Select an option  [Use arrows to move, type to filter]
> Copy command to clipboard
  Explain command
  Exit

Disclaimer: This response was generated by AI.
Always review AI-generated commands before running them.
"""

# ---------------------------------------------------------------------------
# CopilotFilter — matches()
# ---------------------------------------------------------------------------


class TestCopilotStandaloneMatches:
    def setup_method(self) -> None:
        self.f = CopilotFilter()

    def test_matches_bare_binary(self) -> None:
        assert self.f.matches(["copilot"])

    def test_matches_explain_subcommand(self) -> None:
        assert self.f.matches(["copilot", "explain", "git stash"])

    def test_matches_suggest_subcommand(self) -> None:
        assert self.f.matches(["copilot", "suggest", "list files"])

    def test_does_not_match_gh_copilot(self) -> None:
        # gh copilot is GhCopilotFilter's territory, not ours.
        assert not self.f.matches(["gh", "copilot", "explain"])

    def test_does_not_match_empty(self) -> None:
        assert not self.f.matches([])

    def test_does_not_match_unrelated_binary(self) -> None:
        assert not self.f.matches(["npm", "install"])


# ---------------------------------------------------------------------------
# CopilotFilter — compress()
# ---------------------------------------------------------------------------


class TestCopilotStandaloneCompress:
    def setup_method(self) -> None:
        self.f = CopilotFilter()
        self.argv = ["copilot", "explain", "git stash"]

    def _compress(self, stdout: str = _COPILOT_STANDALONE_EXPLAIN) -> str:
        return self.f.compress(stdout, "", 0, self.argv)

    def test_drops_banner(self) -> None:
        result = self._compress()
        assert "GitHub Copilot v1.0.3" not in result
        assert "Authenticated as: octocat" not in result

    def test_drops_spinner(self) -> None:
        result = self._compress()
        assert "Generating..." not in result

    def test_drops_disclaimer(self) -> None:
        result = self._compress()
        assert "Disclaimer:" not in result
        assert "Note:" not in result

    def test_keeps_explanation_body(self) -> None:
        result = self._compress()
        assert "git stash saves uncommitted changes" in result
        assert "git stash pop" in result
        assert "git stash list" in result

    def test_savings_at_least_25_percent(self) -> None:
        result = self._compress()
        original = len(_COPILOT_STANDALONE_EXPLAIN.encode())
        compressed = len(result.encode())
        savings = 1.0 - compressed / original
        assert savings >= 0.25, f"savings={savings:.2%} < 25%"


# ---------------------------------------------------------------------------
# Registration checks
# ---------------------------------------------------------------------------


def test_copilot_registered_in_filters() -> None:
    names = [f.name for f in FILTERS]
    assert "copilot" in names


def test_copilot_in_all_exports() -> None:
    from token_goat import bash_compress

    assert "CopilotFilter" in bash_compress.__all__


def test_copilot_filter_adjacent_to_gh_copilot_filter() -> None:
    """CopilotFilter should immediately follow GhCopilotFilter in FILTERS."""
    names = [f.name for f in FILTERS]
    gh_idx = names.index("gh-copilot")
    cop_idx = names.index("copilot")
    assert cop_idx == gh_idx + 1, (
        f"CopilotFilter (index {cop_idx}) should be immediately after "
        f"GhCopilotFilter (index {gh_idx})"
    )


# ---------------------------------------------------------------------------
# detect_from_command routing
# ---------------------------------------------------------------------------


def test_dispatch_routes_copilot_standalone() -> None:
    result = detect_from_command("copilot explain 'git stash'")
    assert result is not None
    f, _argv = result
    assert f.name == "copilot"


def test_dispatch_does_not_route_gh_copilot_to_standalone() -> None:
    result = detect_from_command("gh copilot explain 'git stash'")
    assert result is not None
    f, _argv = result
    assert f.name == "gh-copilot"


# ---------------------------------------------------------------------------
# GhCopilotFilter improvements
# ---------------------------------------------------------------------------


class TestGhCopilotSuggestWithTarget:
    """GhCopilotFilter should keep the 'Suggested command:' header."""

    def setup_method(self) -> None:
        self.f = GhCopilotFilter()
        self.argv = ["gh", "copilot", "suggest", "--target", "shell", "list files"]

    def test_keeps_suggested_command_header(self) -> None:
        result = self.f.compress(_GH_COPILOT_SUGGEST_WITH_TARGET, "", 0, self.argv)
        assert "Suggested command:" in result

    def test_keeps_the_actual_command(self) -> None:
        result = self.f.compress(_GH_COPILOT_SUGGEST_WITH_TARGET, "", 0, self.argv)
        assert "git stash" in result

    def test_drops_welcome_banner(self) -> None:
        result = self.f.compress(_GH_COPILOT_SUGGEST_WITH_TARGET, "", 0, self.argv)
        assert "Welcome to GitHub Copilot" not in result

    def test_drops_spinner(self) -> None:
        result = self.f.compress(_GH_COPILOT_SUGGEST_WITH_TARGET, "", 0, self.argv)
        assert "Asking GitHub Copilot" not in result

    def test_drops_disclaimer(self) -> None:
        result = self.f.compress(_GH_COPILOT_SUGGEST_WITH_TARGET, "", 0, self.argv)
        assert "Disclaimer:" not in result
        assert "Always review" not in result


class TestGhCopilotMatchesSubcommands:
    def setup_method(self) -> None:
        self.f = GhCopilotFilter()

    def test_does_not_match_alias_subcommand(self) -> None:
        assert not self.f.matches(["gh", "copilot", "alias", "bash"])

    def test_does_not_match_feedback_subcommand(self) -> None:
        assert not self.f.matches(["gh", "copilot", "feedback"])

    def test_matches_explain(self) -> None:
        assert self.f.matches(["gh", "copilot", "explain", "git stash"])

    def test_matches_suggest(self) -> None:
        assert self.f.matches(["gh", "copilot", "suggest", "list files"])
