"""Subprocess wrapper invoked by ``token-goat compress`` to run user commands.

The hook layer rewrites a Bash tool call from::

    pytest -v tests/

to::

    token-goat compress --filter pytest --cmd 'pytest -v tests/'

When the harness executes the rewritten command, control lands in this module
via :func:`run`.  It runs the original command through the system shell,
captures both stdout and stderr, applies the requested filter, prints the
compressed output, records the byte/token savings to the stats DB, and exits
with the *original* exit code so shell chaining (``cmd && next``) still works.

Failure modes
=============

* Command not found → command's exit code surfaces as 127, no compression.
* Wrapper timeout → kills child, prints what was captured so far + a timeout
  marker, exits 124.
* Compression raises → caught at the filter layer (see
  :meth:`bash_compress.Filter.apply`); raw truncation falls through.
* Subprocess crashes (SIGSEGV) → exit code is the negative signal number,
  matching ``bash``'s ``128 + signum`` convention.

Security
========

The wrapper uses ``shell=True`` deliberately: the original command may use
shell features (pipes, redirects, globs, env expansion, command chaining)
that the user wrote intentionally.  The wrapper passes the raw command
string straight to the shell, we do NOT add additional escaping or wrap it
in another layer because the hook already validated the command shape
(:func:`bash_compress.detect_from_command` rejects pipelines / subshells) and
the command string was originally generated by the agent / user, not an
untrusted source.
"""
from __future__ import annotations

__all__ = ["run", "run_compressed", "DEFAULT_TIMEOUT_SECONDS", "MAX_CAPTURE_BYTES"]

import os
import shlex
import signal
import subprocess
import sys
import threading
import time
from collections.abc import Callable
from io import BytesIO
from typing import IO, Final

from . import bash_compress
from .util import get_logger

_LOG = get_logger("bash_runner")

#: Minimum bytes saved to bother writing a stat row.  Filters that squeeze
#: 2–3 bytes (e.g. whitespace-only collapses) generate noise rows with
#: "0.0% savings" in `token-goat stats`; skip them below this threshold.
MIN_RECORD_STAT_BYTES: Final[int] = 32

#: Per-stream byte cap.  Beyond this we stop appending to the in-memory buffer
#: and discard the rest, so a runaway log can never OOM the wrapper.  32 MiB
#: per stream covers practically any real command (10K lines × 3 KB/line).
#: Anything larger than this in either direction is past the point where the
#: model would benefit from seeing the raw output anyway.
MAX_CAPTURE_BYTES: Final[int] = 32 * 1024 * 1024

#: Default wall-clock timeout for the wrapped subprocess, in seconds.  Long
#: enough to cover npm install on a fresh node_modules (~120 s on a slow disk)
#: while bounded enough to surface a hang.  Configurable via the
#: ``--timeout`` CLI flag.
DEFAULT_TIMEOUT_SECONDS: Final[int] = 600

#: Chunk size for non-blocking pipe reads.  64 KiB matches Linux's default
#: pipe buffer size; smaller values would spin the read loop more often.
_READ_CHUNK: Final[int] = 64 * 1024


def _drain_stream_to_buffer(
    stream: IO[bytes] | None,
    buffer: BytesIO,
    cap: int,
    overflow: list[int],
) -> None:
    """Background thread body: copy bytes from *stream* into *buffer* until EOF.

    Uses a hard byte cap so a runaway log cannot fill RAM; once the cap is
    hit further reads are still issued (so the child doesn't block on a full
    pipe buffer) but the data is discarded, with the overflow byte count
    tracked in *overflow[0]* for the wrapper to report.
    """
    if stream is None:
        return
    try:
        while True:
            chunk = stream.read(_READ_CHUNK)
            if not chunk:
                return
            remaining = cap - buffer.tell()
            if remaining <= 0:
                overflow[0] += len(chunk)
                continue
            if len(chunk) > remaining:
                buffer.write(chunk[:remaining])
                overflow[0] += len(chunk) - remaining
            else:
                buffer.write(chunk)
    except (OSError, ValueError) as exc:
        # Pipe closed mid-read or stream object was finalized; harmless at
        # this point because we either captured what we needed or the child
        # exited.  Log at debug only.
        _LOG.debug("drain_stream: %s during read", exc)


def _decode_capture(buf: bytes, overflow: int) -> str:
    """Decode captured bytes as UTF-8 (replace errors); append overflow marker."""
    decoded = buf.decode("utf-8", errors="replace")
    if overflow > 0:
        decoded += (
            f"\n[token-goat: capture capped at {MAX_CAPTURE_BYTES // (1024 * 1024)} MiB;"
            f" {overflow:,} bytes dropped]"
        )
    return decoded


def _spawn(
    cmd: str,
    *,
    cwd: str | None,
    env: dict[str, str] | None,
) -> subprocess.Popen[bytes]:
    """Spawn the wrapped subprocess in shell mode with pipes for stdout/stderr.

    A new process group is created on POSIX (``start_new_session=True``) so
    we can kill the entire pipeline if a timeout fires, ``Popen.kill()`` by
    itself only signals the top-level shell, leaving children running.
    """
    extra: dict[str, object] = {}
    if os.name == "posix":
        extra["start_new_session"] = True
    else:
        # On Windows, CREATE_NEW_PROCESS_GROUP lets us send CTRL_BREAK_EVENT.
        extra["creationflags"] = subprocess.CREATE_NEW_PROCESS_GROUP  # type: ignore[attr-defined]  # CREATE_NEW_PROCESS_GROUP is Windows-only; not in typeshed for POSIX targets
    return subprocess.Popen(  # type: ignore[call-overload]  # noqa: S602, shell=True is intentional; **extra confuses mypy overload resolution
        cmd,
        shell=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        stdin=subprocess.DEVNULL,
        cwd=cwd,
        env=env,
        bufsize=0,
        **extra,
    )


def _kill_process_tree(proc: subprocess.Popen[bytes]) -> None:
    """Terminate the subprocess and all of its descendants.

    On POSIX, sends SIGTERM to the process group then SIGKILL after a grace
    period. On Windows, calls Popen.kill() (TerminateProcess); the new
    process group created by CREATE_NEW_PROCESS_GROUP does not provide a
    tree-kill API, so the best we can do is the top-level shell.
    """
    if proc.poll() is not None:
        return
    if os.name == "posix":
        _posix_kill_tree(proc)
    else:
        try:
            proc.kill()
        except OSError as exc:
            _LOG.debug("kill failed: %s", exc)


def _posix_kill_tree(proc: subprocess.Popen[bytes]) -> None:
    """SIGTERM then SIGKILL the subprocess's process group on POSIX.

    Split out so the body uses POSIX-only ``os.killpg`` / ``os.getpgid`` /
    ``signal.SIGKILL`` attributes that do not exist on Windows. Mypy with
    ``--platform win32`` flags those attributes on the ``os`` and ``signal``
    modules; isolating them in a function called only from the POSIX branch
    keeps the platform check obvious for both humans and the type checker.
    """
    killpg = getattr(os, "killpg", None)
    getpgid = getattr(os, "getpgid", None)
    sigkill = getattr(signal, "SIGKILL", signal.SIGTERM)
    if killpg is None or getpgid is None:
        return
    try:
        killpg(getpgid(proc.pid), signal.SIGTERM)
    except (ProcessLookupError, PermissionError):
        return
    deadline = time.monotonic() + 5.0
    while time.monotonic() < deadline:
        if proc.poll() is not None:
            return
        time.sleep(0.1)
    try:
        killpg(getpgid(proc.pid), sigkill)
    except (ProcessLookupError, PermissionError):
        return


def run(
    command: str,
    *,
    filter_name: str | None = None,
    timeout: int = DEFAULT_TIMEOUT_SECONDS,
    cwd: str | None = None,
    env: dict[str, str] | None = None,
    write_stdout: Callable[[str], object] = sys.stdout.write,
    write_stderr: Callable[[str], object] = sys.stderr.write,
    compression_profile: str | None = None,
    max_tokens: int = 0,
) -> int:
    """Run *command* through the system shell, compress its output, return exit code.

    This is the primary entry point invoked by the ``token-goat compress``
    CLI subcommand.  It returns the wrapped subprocess's exit code so the
    surrounding shell sees the same failure / success signal it would have
    seen without the wrapper.

    Args:
        command:     Raw command string passed verbatim to the shell.  May
                     include shell features (pipes, env expansion, …), the
                     hook layer only wraps commands that don't include
                     pipeline operators, so the operator-containing case
                     would only arise from a manual invocation.
        filter_name: Name of the filter to apply (``"pytest"``, ``"git"``,
                     …).  When ``None``, the wrapper re-runs the dispatch
                     from :mod:`bash_compress` against the command's argv.
                     When no filter matches, the command is run unwrapped
                     (output streamed straight through) so the cost is
                     limited to the subprocess fork.
        timeout:     Wall-clock seconds before the wrapped subprocess is
                     killed.  Defaults to :data:`DEFAULT_TIMEOUT_SECONDS`.
        cwd:         Working directory for the subprocess.  None = inherit.
        env:         Environment for the subprocess.  None = inherit
                     ``os.environ`` so PATH, VIRTUAL_ENV, … are preserved.
        write_stdout: Sink for the compressed output (mockable for tests).
        write_stderr: Sink for wrapper diagnostics (mockable for tests).
        compression_profile: One of ``"aggressive"``, ``"balanced"``, or
            ``"minimal"``.  When ``None`` (default), the value is read from the
            token-goat config file (``config.compression.profile``); if that is
            ``"auto"`` or absent it falls back to ``"balanced"``.

    Returns:
        The exit code of the wrapped subprocess.  124 on wrapper-induced
        timeout (matching ``timeout(1)`` convention).  Negative values map
        to ``128 + |code|`` for parity with shell exit conventions.
    """
    filter_ = _resolve_filter(command, filter_name)
    if filter_ is None:
        # No filter applies, exec the command transparently.  We could skip
        # the subprocess and use os.execvp for zero overhead, but that loses
        # the timeout protection; the wrapper subprocess cost is ~5 ms.
        return _passthrough(command, timeout=timeout, cwd=cwd, env=env)

    # Resolve effective compression profile: explicit argument wins; otherwise
    # read from config (ignoring "auto" since harness detection is unavailable
    # in the wrapper subprocess — the hook already resolved it before spawning).
    effective_profile = compression_profile
    if effective_profile is None:
        try:
            from . import config as _cfg_mod  # noqa: PLC0415
            _cfg_profile = _cfg_mod.load().compression.profile
            effective_profile = _cfg_profile if _cfg_profile != "auto" else "balanced"
        except Exception:  # noqa: BLE001
            effective_profile = "balanced"

    return _wrap_and_compress(
        command,
        filter_,
        timeout=timeout,
        cwd=cwd,
        env=env,
        write_stdout=write_stdout,
        write_stderr=write_stderr,
        compression_profile=effective_profile,
        max_tokens=max_tokens,
    )


# Alias for clarity at the public API surface.
run_compressed = run


def _resolve_filter(
    command: str, filter_name: str | None,
) -> bash_compress.Filter | None:
    """Look up the filter by name first, falling back to argv-based dispatch."""
    if filter_name:
        named = bash_compress.filter_by_name(filter_name)
        if named is not None:
            return named
        _LOG.debug("filter_name=%s not registered; falling back to auto-detect", filter_name)
    try:
        argv = shlex.split(command, posix=True)
    except ValueError:
        return None
    return bash_compress.select_filter(argv)


def _passthrough(
    command: str, *, timeout: int, cwd: str | None, env: dict[str, str] | None,
) -> int:
    """Run *command* with no compression, streaming stdout/stderr unchanged.

    Used when no filter applies (and therefore the wrapper would be pure
    overhead).  Still runs through ``subprocess`` so the timeout takes effect;
    a future optimisation could ``os.execvp`` here for zero overhead but
    would lose the timeout safeguard.
    """
    try:
        proc = subprocess.run(  # noqa: S602, shell=True is intentional
            command,
            shell=True,
            cwd=cwd,
            env=env,
            timeout=timeout,
            check=False,
        )
        return proc.returncode
    except subprocess.TimeoutExpired:
        return 124
    except FileNotFoundError:
        return 127


def _wrap_and_compress(
    command: str,
    filter_: bash_compress.Filter,
    *,
    timeout: int,
    cwd: str | None,
    env: dict[str, str] | None,
    write_stdout: Callable[[str], object],
    write_stderr: Callable[[str], object],
    compression_profile: str = "balanced",
    max_tokens: int = 0,
) -> int:
    """Run *command* with output capture, apply *filter_*, print result.

    Captures up to :data:`MAX_CAPTURE_BYTES` per stream via background
    threads.  Background threads (rather than ``proc.communicate()``) let the
    timeout fire promptly: ``communicate`` blocks on EOF, which a hung
    subprocess never produces.
    """
    start = time.monotonic()
    timed_out = False
    proc = _spawn(command, cwd=cwd, env=env)
    stdout_buf = BytesIO()
    stderr_buf = BytesIO()
    stdout_overflow = [0]
    stderr_overflow = [0]
    t_out = threading.Thread(
        target=_drain_stream_to_buffer,
        args=(proc.stdout, stdout_buf, MAX_CAPTURE_BYTES, stdout_overflow),
        daemon=True,
    )
    t_err = threading.Thread(
        target=_drain_stream_to_buffer,
        args=(proc.stderr, stderr_buf, MAX_CAPTURE_BYTES, stderr_overflow),
        daemon=True,
    )
    t_out.start()
    t_err.start()
    try:
        proc.wait(timeout=timeout)
    except subprocess.TimeoutExpired:
        timed_out = True
        _kill_process_tree(proc)
        try:
            proc.wait(timeout=5)
        except subprocess.TimeoutExpired:
            _LOG.warning("subprocess refused to die after kill; abandoning")
    finally:
        t_out.join(timeout=2)
        t_err.join(timeout=2)
        for stream in (proc.stdout, proc.stderr):
            if stream is not None:
                with _suppress_close():
                    stream.close()

    exit_code = proc.returncode if not timed_out else 124
    stdout_text = _decode_capture(stdout_buf.getvalue(), stdout_overflow[0])
    stderr_text = _decode_capture(stderr_buf.getvalue(), stderr_overflow[0])
    if timed_out:
        stderr_text = (stderr_text + "\n") if stderr_text else ""
        stderr_text += (
            f"[token-goat: command exceeded {timeout}s timeout and was killed]"
        )

    try:
        argv = shlex.split(command, posix=True)
    except ValueError:
        argv = [command]

    result = bash_compress.compress_output(
        filter_, stdout_text, stderr_text, exit_code, argv,
        compression_profile=compression_profile,
    )
    # Apply pressure-scaled cap to the text portion BEFORE appending the compression
    # summary marker so the marker survives truncation and remains visible to the agent.
    text = result.text
    if max_tokens > 0:
        text = bash_compress.cap_tokens(text, max_tokens)
    marker = result.with_marker()[len(result.text):]  # "" when bytes_saved <= 0
    body = text + marker
    write_stdout(body + ("\n" if not body.endswith("\n") else ""))

    elapsed_ms = (time.monotonic() - start) * 1000
    _record_savings(result, command, elapsed_ms)
    return exit_code


class _suppress_close:  # noqa: N801, context-manager naming
    """Context manager that swallows close-time exceptions on pipe handles."""

    def __enter__(self) -> _suppress_close:
        return self

    def __exit__(self, exc_type, exc, tb) -> bool:  # noqa: ANN001
        return exc_type in (OSError, ValueError, AttributeError)


def _record_savings(
    result: bash_compress.CompressedOutput, command: str, elapsed_ms: float,
) -> None:
    """Write the bash_compress savings stat to the global stats DB.

    Best-effort: a DB error must never block the wrapper from returning the
    exit code.  All exceptions are caught and logged at debug level.
    """
    if result.bytes_saved < MIN_RECORD_STAT_BYTES:
        return
    try:
        from . import db  # noqa: PLC0415

        # Use a bounded, sanitized form of the command for the detail field.
        from .hooks_common import sanitize_log_str  # noqa: PLC0415

        detail = sanitize_log_str(command, max_len=256)
        db.record_stat(
            None,
            f"bash_compress:{result.filter_name}",
            bytes_saved=result.bytes_saved,
            tokens_saved=result.tokens_saved,
            detail=detail,
        )
        _LOG.info(
            "bash_compress %s saved %d bytes (%d tokens) in %.0f ms",
            result.filter_name,
            result.bytes_saved,
            result.tokens_saved,
            elapsed_ms,
        )
    except Exception as exc:  # noqa: BLE001
        _LOG.debug("record_savings failed: %s", exc)
