"""Summarize lock files and dependency specs to compact direct-dep tables."""
from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from pathlib import Path


@dataclass
class DepEntry:
    name: str
    version: str
    extras: str = ""


@dataclass
class LockResult:
    format: str
    entries: list[DepEntry] = field(default_factory=list)
    source_path: str = ""

    @property
    def count(self) -> int:
        return len(self.entries)


# ---------------------------------------------------------------------------
# Format detection
# ---------------------------------------------------------------------------


def _detect_format(path: Path, text: str) -> str:
    name = path.name.lower()
    if name == "poetry.lock":
        return "poetry"
    if name == "uv.lock":
        return "uv"
    if name == "package-lock.json":
        return "npm"
    if name in ("pipfile.lock",):
        return "pipfile"
    if name == "cargo.lock":
        return "cargo"
    if name in ("requirements.txt", "requirements-dev.txt", "requirements-test.txt") or name.startswith("requirements"):
        return "requirements"
    if name == "yarn.lock":
        return "yarn"
    # Content-based fallback
    if text.startswith("# This file is automatically @generated by uv"):
        return "uv"
    if '[[package]]' in text and 'name = "' in text and 'version = "' in text:
        return "poetry"
    if '"lockfileVersion"' in text:
        return "npm"
    return "requirements"


# ---------------------------------------------------------------------------
# Parsers
# ---------------------------------------------------------------------------


def _parse_poetry(text: str) -> list[DepEntry]:
    """Parse poetry.lock — all packages (no transitive distinction without pyproject.toml)."""
    entries: list[DepEntry] = []
    for block in re.split(r"\[\[package\]\]", text)[1:]:
        name_m = re.search(r'^name\s*=\s*"(.+?)"', block, re.MULTILINE)
        ver_m = re.search(r'^version\s*=\s*"(.+?)"', block, re.MULTILINE)
        opt_m = re.search(r'^optional\s*=\s*true', block, re.MULTILINE)
        if name_m and ver_m and not opt_m:
            entries.append(DepEntry(name=name_m.group(1), version=ver_m.group(1)))
    entries.sort(key=lambda e: e.name.lower())
    return entries


def _parse_uv(text: str) -> list[DepEntry]:
    """Parse uv.lock — same TOML structure as poetry.lock."""
    entries: list[DepEntry] = []
    for block in re.split(r"\[\[package\]\]", text)[1:]:
        name_m = re.search(r'^name\s*=\s*"(.+?)"', block, re.MULTILINE)
        ver_m = re.search(r'^version\s*=\s*"(.+?)"', block, re.MULTILINE)
        if name_m and ver_m:
            entries.append(DepEntry(name=name_m.group(1), version=ver_m.group(1)))
    entries.sort(key=lambda e: e.name.lower())
    return entries


def _parse_npm(text: str) -> list[DepEntry]:
    """Parse package-lock.json — extract packages with resolved versions."""
    try:
        data = json.loads(text)
    except json.JSONDecodeError:
        return []

    entries: list[DepEntry] = []

    # v2/v3 format: "packages" key
    packages = data.get("packages", {})
    if packages:
        for pkg_path, info in packages.items():
            if pkg_path == "" or not isinstance(info, dict):
                continue
            if info.get("dev") or info.get("peer"):
                continue
            # Direct deps appear at depth 1: "node_modules/name"
            parts = pkg_path.split("node_modules/")
            if len(parts) == 2 and "/" not in parts[1].lstrip("@").replace("/", "", 1 if parts[1].startswith("@") else 0):
                name = parts[1]
                version = info.get("version", "")
                entries.append(DepEntry(name=name, version=version))
    else:
        # v1 format: "dependencies" key
        for name, info in data.get("dependencies", {}).items():
            if isinstance(info, dict) and not info.get("dev"):
                entries.append(DepEntry(name=name, version=info.get("version", "")))

    entries.sort(key=lambda e: e.name.lower())
    return entries


def _parse_pipfile(text: str) -> list[DepEntry]:
    """Parse Pipfile.lock — read 'default' section."""
    try:
        data = json.loads(text)
    except json.JSONDecodeError:
        return []
    entries: list[DepEntry] = []
    for name, info in data.get("default", {}).items():
        if isinstance(info, dict):
            version = re.sub(r"^==", "", info.get("version", ""))
            entries.append(DepEntry(name=name, version=version))
    entries.sort(key=lambda e: e.name.lower())
    return entries


def _parse_cargo(text: str) -> list[DepEntry]:
    """Parse Cargo.lock — [[package]] sections, all entries."""
    entries: list[DepEntry] = []
    for block in re.split(r"\[\[package\]\]", text)[1:]:
        name_m = re.search(r'^name\s*=\s*"(.+?)"', block, re.MULTILINE)
        ver_m = re.search(r'^version\s*=\s*"(.+?)"', block, re.MULTILINE)
        if name_m and ver_m:
            entries.append(DepEntry(name=name_m.group(1), version=ver_m.group(1)))
    entries.sort(key=lambda e: e.name.lower())
    return entries


def _parse_requirements(text: str) -> list[DepEntry]:
    """Parse requirements.txt — skip comments, options, and URLs."""
    entries: list[DepEntry] = []
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith(("#", "-", "http://", "https://", "git+")):
            continue
        # Strip environment markers: name[extras]==ver ; python_version >= "3.8"
        line = re.split(r"\s*;", line)[0].strip()
        # Parse extras: requests[security]==2.31.0
        m = re.match(r"^([A-Za-z0-9_.\-]+)(\[.+?\])?\s*([~=!<>]+\S+)?", line)
        if m:
            name = m.group(1)
            extras = m.group(2) or ""
            version = m.group(3) or ""
            # Normalize: ==1.2.3 → 1.2.3
            version = re.sub(r"^[~=!<>]+", "", version)
            entries.append(DepEntry(name=name, version=version, extras=extras))
    entries.sort(key=lambda e: e.name.lower())
    return entries


def _parse_yarn(text: str) -> list[DepEntry]:
    """Parse yarn.lock (v1 classic format)."""
    entries: list[DepEntry] = []
    seen: set[str] = set()
    i = 0
    lines = text.splitlines()
    while i < len(lines):
        line = lines[i]
        # Package header: "name@range, name@range:"
        if line and not line.startswith(" ") and not line.startswith("#") and line.endswith(":"):
            # Extract base name (before @)
            spec = line.rstrip(":")
            first = spec.split(",")[0].strip().strip('"')
            name_m = re.match(r"^(@?[^@]+)@", first)
            if name_m:
                name = name_m.group(1)
                # Find version line
                ver = ""
                j = i + 1
                while j < len(lines) and lines[j].startswith(" "):
                    vm = re.match(r'^\s+version\s+"(.+?)"', lines[j])
                    if vm:
                        ver = vm.group(1)
                        break
                    j += 1
                if name not in seen:
                    seen.add(name)
                    entries.append(DepEntry(name=name, version=ver))
        i += 1
    entries.sort(key=lambda e: e.name.lower())
    return entries


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def summarize_lockfile(path: Path) -> LockResult:
    """Read a lock file and return a compact dep table."""
    text = path.read_text(encoding="utf-8", errors="replace")
    fmt = _detect_format(path, text)
    result = LockResult(format=fmt, source_path=str(path))

    if fmt == "poetry":
        result.entries = _parse_poetry(text)
    elif fmt == "uv":
        result.entries = _parse_uv(text)
    elif fmt == "npm":
        result.entries = _parse_npm(text)
    elif fmt == "pipfile":
        result.entries = _parse_pipfile(text)
    elif fmt == "cargo":
        result.entries = _parse_cargo(text)
    elif fmt == "yarn":
        result.entries = _parse_yarn(text)
    else:
        result.entries = _parse_requirements(text)

    return result


def format_lockdeps_text(result: LockResult) -> str:
    if not result.entries:
        return "No dependencies found."

    name_w = max(len(e.name) + len(e.extras) for e in result.entries)
    name_w = max(name_w, 4)
    ver_w = max((len(e.version) for e in result.entries), default=7)
    ver_w = max(ver_w, 7)

    header = f"{'Package':<{name_w}}  {'Version':<{ver_w}}"
    sep = f"{'─' * name_w}  {'─' * ver_w}"
    lines = [header, sep]
    for e in result.entries:
        name_col = f"{e.name}{e.extras}"
        lines.append(f"{name_col:<{name_w}}  {e.version:<{ver_w}}")

    lines.append("")
    lines.append(f"{result.count} package(s)  [{result.format}]")
    if result.source_path:
        lines.append(f"Source: {result.source_path}")
    return "\n".join(lines)


def format_lockdeps_json(result: LockResult) -> str:
    return json.dumps(
        {
            "format": result.format,
            "count": result.count,
            "packages": [
                {"name": e.name, "version": e.version, "extras": e.extras}
                for e in result.entries
            ],
        },
        indent=2,
    )
